"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import { Providers } from "@/redux/provider";
import { ColorModeContext, tokens, useMode } from "@/theme";
import { Box, CssBaseline, ThemeProvider } from "@mui/material";
import { SnackbarProvider } from "notistack";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [theme, colorMode] = useMode();
  const colors = tokens(theme.palette.mode);
  return (
    <html lang="en">
      <body className={inter.className}>
        <ColorModeContext.Provider value={colorMode}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Providers>
              <Box className="app  bg-[#2E2C2C]">
                <main className="content">
                  <SnackbarProvider maxSnack={3} preventDuplicate>
                    <Box
                      className="flex flex-row rounded-xl h-full w-full"
                      backgroundColor={colors.bg3}
                    >
                      <Box
                        backgroundColor={colors.bgNav}
                        className="min-w-[80px]"
                      >
                        <Sidebar />
                      </Box>
                      {children}
                    </Box>
                  </SnackbarProvider>
                </main>
              </Box>
            </Providers>
          </ThemeProvider>
        </ColorModeContext.Provider>
      </body>
    </html>
  );
}
